"""Regenerate or check the deterministic Semantic IR fixture corpus."""

from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "fixtures"
MANIFEST = FIXTURES / "manifest.json"
DEFAULT_OUTPUT = FIXTURES / "expected"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from semantic_verifier.backend import create_backend  # noqa: E402
from semantic_verifier.dump import dump_module  # noqa: E402
from semantic_verifier.pipeline import VerificationPipeline  # noqa: E402


def _relative_path(value: str) -> PurePosixPath:
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"fixture path must stay relative: {value!r}")
    return path


def load_manifest() -> dict[str, Any]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema") != "codeskeptic.fixture-corpus/v0":
        raise ValueError("unsupported fixture manifest schema")
    cases = manifest.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValueError("fixture manifest must contain at least one case")
    names = [str(case.get("name", "")) for case in cases]
    if len(names) != len(set(names)):
        raise ValueError("fixture case names must be unique")
    return manifest


def generate(*, z3: str | None = None) -> dict[PurePosixPath, bytes]:
    manifest = load_manifest()
    pipeline = VerificationPipeline()
    pipeline.checker = create_backend("both", z3=z3)
    artifacts: dict[PurePosixPath, bytes] = {}
    for case in manifest["cases"]:
        name = str(case["name"])
        source_relative = _relative_path(str(case["source"]))
        source_path = FIXTURES.joinpath(*source_relative.parts)
        source = source_path.read_text(encoding="utf-8")
        display_path = (PurePosixPath("fixtures") / source_relative).as_posix()
        report = pipeline.verify_source(source, display_path=display_path)
        actual_summary = report.summary()
        if actual_summary != case["expected_summary"]:
            raise ValueError(
                f"fixture {name!r} summary changed: "
                f"expected {case['expected_summary']}, got {actual_summary}"
            )
        artifacts[PurePosixPath(f"{name}.ir")] = dump_module(
            report.module
        ).encode("utf-8")
        artifacts[PurePosixPath(f"{name}.report.json")] = report.to_json().encode(
            "utf-8"
        )
    return artifacts


def write_artifacts(output: Path, artifacts: dict[PurePosixPath, bytes]) -> None:
    output.mkdir(parents=True, exist_ok=True)
    for relative, content in artifacts.items():
        target = output.joinpath(*relative.parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)


def check_artifacts(
    output: Path, artifacts: dict[PurePosixPath, bytes]
) -> list[str]:
    mismatches: list[str] = []
    expected_names = {relative.as_posix() for relative in artifacts}
    actual_names = {
        path.relative_to(output).as_posix()
        for path in output.rglob("*")
        if path.is_file()
    } if output.exists() else set()
    for missing in sorted(expected_names - actual_names):
        mismatches.append(f"missing: {missing}")
    for unexpected in sorted(actual_names - expected_names):
        mismatches.append(f"unexpected: {unexpected}")
    for relative, content in artifacts.items():
        target = output.joinpath(*relative.parts)
        if target.is_file() and target.read_bytes() != content:
            mismatches.append(f"changed: {relative.as_posix()}")
    return mismatches


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed fixtures differ from regenerated bytes",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="destination directory (default: fixtures/expected)",
    )
    parser.add_argument(
        "--z3",
        help="path to Z3 (otherwise SEMANTIC_VERIFIER_Z3/PATH is used)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    try:
        artifacts = generate(z3=arguments.z3)
        output = arguments.output_dir.resolve()
        if arguments.check:
            mismatches = check_artifacts(output, artifacts)
            if mismatches:
                for mismatch in mismatches:
                    print(mismatch, file=sys.stderr)
                return 1
            print(f"fixtures are current ({len(artifacts)} artifacts)")
            return 0
        write_artifacts(output, artifacts)
        print(f"wrote {len(artifacts)} artifacts to {output}")
        return 0
    except Exception as error:
        print(f"fixture regeneration failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
